# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DistrictMapExtractor
                                 A QGIS plugin
 This plugin will help you prepare desired location to work with from the Map of Malawi
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-24
        copyright            : (C) 2023 by unitech Inc
        email                : info@unitech.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DistrictMapExtractor class from file DistrictMapExtractor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .district_map_extractor import DistrictMapExtractor
    return DistrictMapExtractor(iface)
